name: kioub_attack
description: "Mobile game made with Flame for Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.13.1
  flame_audio: ^2.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/bomb.png
    - assets/images/e-0.png
    - assets/images/e-1.png
    - assets/images/e-2.png
    - assets/images/e-3.png
    - assets/images/e-4.png
    - assets/images/e-5.png
    - assets/images/e-6.png
    - assets/images/e-7.png
    - assets/images/e-8.png
    - assets/images/e-9.png
    - assets/images/e-10.png
    - assets/images/e-11.png
    - assets/images/e-12.png
    - assets/images/e-13.png
    - assets/images/monster-1.png
    - assets/images/monster-2.png
    - assets/images/monster-3.png
    - assets/images/monster-4.png
    - assets/audio/explosion.mp3
    - assets/audio/music.mp3

  fonts:
    - family: Thirteen-Pixel-Fonts
      fonts:
        - asset: fonts/Thirteen-Pixel-Fonts.ttf
